version: '{build}'
image:
- Visual Studio 2019
environment:
  NUGET_API_KEY:
    secure: qG9Vskx9xsjJZq55dQJL5u8NY4NtUfKui2CqKlmmRSluU7jQlB8YwUncQQYfVVxz
  BUILD_BOT_PASSWORD:
    secure: wJ9JVS5hSAp9ItYlHKxTPg==
build_script:
- cmd: .\build.cmd publish "--trigger=%APPVEYOR_REPO_TAG_NAME%" "--build-number=%APPVEYOR_BUILD_NUMBER%"
test: off
install:
- cmd: '"C:\Program Files (x86)\Android\android-sdk\tools\bin\sdkmanager.bat" --licenses < tools\yes.txt > nul'
- cmd: '"C:\Program Files (x86)\Android\android-sdk\tools\bin\sdkmanager.bat" --update'
- cmd: '"C:\Program Files (x86)\Android\android-sdk\tools\bin\sdkmanager.bat" "build-tools;27.0.3" "platforms;android-27"'
artifacts:
- path: release\*.nupkg
