version: '{build}'
image:
- Visual Studio 2017
environment:
  NUGET_API_KEY:
    secure: RJ0TZqHfLpBHVwWjG6cJfG37zcAE1IImJVKfs5tbD0dUL066cJNf+cZr0egrgfTG
  BUILD_BOT_PASSWORD:
    secure: wJ9JVS5hSAp9ItYlHKxTPg==
build_script:
- cmd: .\build.cmd publish "--trigger=%APPVEYOR_REPO_TAG_NAME%" "--build-number=%APPVEYOR_BUILD_NUMBER%"
test: off
artifacts:
- path: 'release\*.nupkg'
