version: '{build}'
image:
- Visual Studio 2019
environment:
  NUGET_API_KEY:
    secure: /FLJCPNtLDyXDbw62wnY4tBc3kRJMPNbttutkzVhCdUDEmg9pjEBGZnBVpBTemKK
  BUILD_BOT_PASSWORD:
    secure: wJ9JVS5hSAp9ItYlHKxTPg==
build_script:
- cmd: .\build.cmd publish "--trigger=%APPVEYOR_REPO_TAG_NAME%" "--build-number=%APPVEYOR_BUILD_NUMBER%"
test: off
