version: '3'

services:
  jekyll:
    image: jekyll/jekyll:pages
    container_name: System.Data.SQLite
    command: jekyll serve --force_polling --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./:/srv/jekyll
